### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by uselessdumbaccount1321** [TuxHurt/TuxHurt#15]
I don't know if you are still on this, but when i tried to run the run.py, I got this error
![image](https://user-images.githubusercontent.com/39642756/176275635-3014d8e1-c797-4d45-8c18-859c6b595b29.png)
I have colorama and everything else installed, can you please help me out on this?

**Comment by ghost** [comment]
That's not a TuxHurt issue. You may have a corrupted version of colorama, you should try reinstalling it with `python3 -m pip install colorama`

**Comment by taskscheduler** [comment]
> That's not a TuxHurt issue. You may have a corrupted version of colorama, you should try reinstalling it with `python3 -m pip install colorama`

The Comment above is the Solution. The issue has nothing to do with TuxHurt.
